### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Anzic23** [instalator/ioBroker.mikrotik#28]
log:
```

2020-02-28 11:34:38.451 - error: mikrotik.1 (16432) uncaught exception: Cannot read property 'replace' of undefined
--
2020-02-28 11:34:38.452 - error: mikrotik.1 (16432) TypeError: Cannot read property 'replace' of undefined
at Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:557:70)
at Array.forEach ()
at states.(anonymous function).forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:543:45)
at Array.forEach ()
at SetStates.Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:542:25)
at Array.forEach ()
at SetStates (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:540:25)
at ch8 (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:347:41)
at Channel.ch.once (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:326:23)
at Object.onceWrapper (events.js:286:20)
2020-02-28 11:34:38.457 - info: mikrotik.1 (16432) terminating
2020-02-28 11:34:38.458 - info: mikrotik.1 (16432) Terminated (NO_ERROR): Without reason
2020-02-28 11:34:39.003 - error: host.iobroker Caught by controller[0]: TypeError: Cannot read property 'replace' of undefined
2020-02-28 11:34:39.003 - error: host.iobroker Caught by controller[0]: at Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:557:70)
2020-02-28 11:34:39.003 - error: host.iobroker Caught by controller[0]: at Array.forEach ()
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at states.(anonymous function).forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:543:45)
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at Array.forEach ()
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at SetStates.Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:542:25)
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at Array.forEach ()
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at SetStates (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:540:25)
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at ch8 (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:347:41)
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at Channel.ch.once (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:326:23)
2020-02-28 11:34:39.004 - error: host.iobroker Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
2020-02-28 11:34:39.004 - info: host.iobroker instance system.adapter.mikrotik.1 terminated with code 0 (NO_ERROR)
2020-02-28 11:34:39.005 - info: host.iobroker Restart adapter system.adapter.mikrotik.1 because enabled
2020-02-28 11:35:09.021 - info: host.iobroker instance system.adapter.mikrotik.1 started with pid 23508
2020-02-28 11:35:10.904 - info: mikrotik.1 (23508) starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.mikrotik, node: v10.19.0
2020-02-28 11:35:10.984 - info: mikrotik.1 (23508) MikroTik Connected to: 192.168.1.1
2020-02-28 11:35:22.934 - error: mikrotik.1 (23508) uncaught exception: Cannot read property 'replace' of undefined
2020-02-28 11:35:22.934 - error: mikrotik.1 (23508) TypeError: Cannot read property 'replace' of undefined
at Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:557:70)
at Array.forEach ()
at states.(anonymous function).forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:543:45)
at Array.forEach ()
at SetStates.Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:542:25)
at Array.forEach ()
at SetStates (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:540:25)
at ch8 (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:347:41)
at Channel.ch.once (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:326:23)
at Object.onceWrapper (events.js:286:20)
2020-02-28 11:35:22.940 - info: mikrotik.1 (23508) terminating
2020-02-28 11:35:22.941 - info: mikrotik.1 (23508) Terminated (NO_ERROR): Without reason
2020-02-28 11:35:23.469 - error: host.iobroker Caught by controller[0]: TypeError: Cannot read property 'replace' of undefined
2020-02-28 11:35:23.469 - error: host.iobroker Caught by controller[0]: at Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:557:70)
2020-02-28 11:35:23.469 - error: host.iobroker Caught by controller[0]: at Array.forEach ()
2020-02-28 11:35:23.469 - error: host.iobroker Caught by controller[0]: at states.(anonymous function).forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:543:45)
2020-02-28 11:35:23.470 - error: host.iobroker Caught by controller[0]: at Array.forEach ()
2020-02-28 11:35:23.470 - error: host.iobroker Caught by controller[0]: at SetStates.Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:542:25)
2020-02-28 11:35:23.470 - error: host.iobroker Caught by controller[0]: at Array.forEach ()
2020-02-28 11:35:23.470 - error: host.iobroker Caught by controller[0]: at SetStates (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:540:25)
2020-02-28 11:35:23.470 - error: host.iobroker Caught by controller[0]: at ch8 (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:347:41)
2020-02-28 11:35:23.470 - error: host.iobroker Caught by controller[0]: at Channel.ch.once (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:326:23)
2020-02-28 11:35:23.470 - error: host.iobroker Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
2020-02-28 11:35:23.473 - info: host.iobroker instance system.adapter.mikrotik.1 terminated with code 0 (NO_ERROR)
2020-02-28 11:35:23.473 - info: host.iobroker Restart adapter system.adapter.mikrotik.1 because enabled
2020-02-28 11:35:53.490 - info: host.iobroker instance system.adapter.mikrotik.1 started with pid 23638
2020-02-28 11:35:55.137 - info: mikrotik.1 (23638) starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.mikrotik, node: v10.19.0
2020-02-28 11:35:55.218 - info: mikrotik.1 (23638) MikroTik Connected to: 192.168.1.1


```

**Comment by instalator** [comment]
Обнови с гитхаба и дай лог при падении

**Comment by Anzic23** [comment]
```
2020-03-16 02:14:49.446  - [31merror[39m: mikrotik.1 (3332) uncaught exception: Cannot read property 'replace' of undefined
2020-03-16 02:14:49.446  - [31merror[39m: mikrotik.1 (3332) TypeError: Cannot read property 'replace' of undefined
    at Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:558:70)
    at Array.forEach (<anonymous>)
    at states.(anonymous function).forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:543:45)
    at Array.forEach (<anonymous>)
    at SetStates.Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:542:25)
    at Array.forEach (<anonymous>)
    at SetStates (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:540:25)
    at ch8 (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:347:41)
    at Channel.ch.once (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:326:23)
    at Object.onceWrapper (events.js:286:20)
2020-03-16 02:14:49.451  - [32minfo[39m: mikrotik.1 (3332) terminating
2020-03-16 02:14:49.452  - [32minfo[39m: mikrotik.1 (3332) Terminated (NO_ERROR): Without reason
2020-03-16 02:14:49.997  - [31merror[39m: host.iobroker Caught by controller[0]: TypeError: Cannot read property 'replace' of undefined
2020-03-16 02:14:49.998  - [31merror[39m: host.iobroker Caught by controller[0]:     at Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:558:70)
2020-03-16 02:14:49.998  - [31merror[39m: host.iobroker Caught by controller[0]:     at Array.forEach (<anonymous>)
2020-03-16 02:14:49.998  - [31merror[39m: host.iobroker Caught by controller[0]:     at states.(anonymous function).forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:543:45)
2020-03-16 02:14:49.998  - [31merror[39m: host.iobroker Caught by controller[0]:     at Array.forEach (<anonymous>)
2020-03-16 02:14:49.998  - [31merror[39m: host.iobroker Caught by controller[0]:     at SetStates.Object.keys.forEach (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:542:25)
2020-03-16 02:14:49.998  - [31merror[39m: host.iobroker Caught by controller[0]:     at Array.forEach (<anonymous>)
2020-03-16 02:14:49.999  - [31merror[39m: host.iobroker Caught by controller[0]:     at SetStates (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:540:25)
2020-03-16 02:14:49.999  - [31merror[39m: host.iobroker Caught by controller[0]:     at ch8 (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:347:41)
2020-03-16 02:14:49.999  - [31merror[39m: host.iobroker Caught by controller[0]:     at Channel.ch.once (/opt/iobroker/node_modules/iobroker.mikrotik/main.js:326:23)
2020-03-16 02:14:49.999  - [31merror[39m: host.iobroker Caught by controller[0]:     at Object.onceWrapper (events.js:286:20)
2020-03-16 02:14:49.999  - [32minfo[39m: host.iobroker instance system.adapter.mikrotik.1 terminated with code 0 (NO_ERROR)
2020-03-16 02:14:49.999  - [32minfo[39m: host.iobroker Restart adapter system.adapter.mikrotik.1 because enabled
```

**Comment by instalator** [comment]
По непонятной причине микротик отдает не весь список DHCP клиентов.
[.................. , "!re","=.id=*4967","=address=192.168.1.39","=mac-address=78:11:DC:DF:DE:DB","=address-lists=","=server=defconf","=dhcp-option=","=status=bound","=expires-after=8m27s","=last-seen=1m33s","=active-address=192.168.1.39","=active-mac-address=78:11:DC:DF:DE:DB","=active-server=defconf","=host-name=air","=radius=false","=dynamic=false","=blocked=false","=disabled=false",**"!re"**]
API отдает массив в котором клиенты разбиты тегом !re (идет в начале). В какой то момент в конце этого массива появляется тег начала !re.
Необходимо проверить версию с гитхаба, если ошибка не будет повторяться, то апну версию в репу

**Comment by Anzic23** [comment]
Сутки, полет нормальный
